Repository Seagate/cortx-test, pull requests merged in 2022-06, with the labels that each got.

#1543 Delete user policy
  comptests/s3/test_rest_api_rgw.py
  libs/s3/s3_iam_rest_rgw.py
Labels: cla-signed

#1615 Codacy fix part 2
  config/prov/prov_test.yaml
  libs/prov/prov_k8s_cortx_deploy.py
  libs/prov/provisioner.py
  scripts/cicd_k8s_cortx_deploy/create_db_entry.py
  tests/prov/test_cont_deployment.py
  tests/prov/test_post_deploy_validation.py
  tests/prov/test_prov_single_node.py
Labels: cla-signed

#1623 Skip marker removal from server file
  tests/ha/test_server_pod_failure.py
Labels: cla-signed

#1619 added test code
  tests/dtm/test_single_process_restart.py
Labels: cla-signed

#1627 Added the error message handling
  libs/prov/prov_k8s_cortx_deploy.py
Labels: cla-signed

#1624 core and test lib
  libs/s3/s3_versioning.py
  libs/s3/s3_versioning_test_lib.py
Labels: cla-signed

#1626 Test additions for CICD sanity pipeline
  tests/s3/test_bucket_tagging.py
  tests/s3/versioning/test_put_bucket_versioning.py
  tests/s3/versioning/test_versioning_put_object.py
Labels: cla-signed

#1625 in-progress : CORTX-31921 : purge data feature branch test updated
  config/csm/test_rest_iam_user.yaml
  libs/csm/rest/csm_rest_iamuser.py
  libs/s3/s3_misc.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1633 Revert "in-progress : CORTX-31921 : purge data feature branch test updated"
  config/csm/test_rest_iam_user.yaml
  libs/csm/rest/csm_rest_iamuser.py
  libs/s3/s3_misc.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1630 CORTX-31923: GET/HEAD Object tests RBF
  libs/s3/s3_versioning_common_test_lib.py
  tests/s3/versioning/test_list_object_versions.py
  tests/s3/versioning/test_versioning_delete_object.py
  tests/s3/versioning/test_versioning_get_head_object.py
Labels: cla-signed

#1634 CORTX-31921 : purge data feature branch test updated
  config/csm/test_rest_iam_user.yaml
  libs/csm/rest/csm_rest_iamuser.py
  libs/s3/s3_misc.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1632 CPRTX_31878:_TEST_40435
  libs/s3/s3_tagging_test_lib.py
  libs/s3/s3_versioning_common_test_lib.py
  tests/s3/versioning/test_delete_object_tagging.py
Labels: cla-signed

#1629 F 20c rbf rgw
  commons/error_messages.py
  config/s3/test_multipart_upload.yaml
  tests/s3/multipart_upload/test_multipart_abort_copy.py
  tests/s3/test_object_workflow_operations.py
Labels: cla-signed

#1631 restructured the upgrade methods in new file
  commons/commands.py
  comptests/prov/test_prov_k8s_cortx_granular.py
  comptests/prov/test_prov_k8s_cortx_upgrade.py
  config/prov/prov_test.yaml
  libs/prov/prov_k8s_cortx_deploy.py
  libs/prov/prov_k8s_cortx_upgrade.py
  scripts/cicd_k8s_cortx_deploy/create_db_entry.py
  tests/prov/test_prov_k8s_cortx_upgrade.py
Labels: cla-signed

#1635 F-71A List IAM Users RBF
  config/csm/rest_response_data.yaml
  config/csm/test_rest_iam_user.yaml
  tests/csm/rest/test_capacity_quota.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1641 Cortx-Namespace and PVC_List
  comptests/prov/test_prov_k8s_cortx.py
Labels: cla-signed

#1622 Cont rd wr del server process tests
  config/test_dtm_config.yaml
  libs/dtm/dtm_recovery.py
  tests/dtm/test_rgw_s3_process_restart.py
  tests/dtm/test_single_process_restart.py
Labels: cla-signed

#1644 Patch_F-451: moved method from test IAM users to libs.
  libs/csm/rest/csm_rest_iamuser.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1639 modified for rgw limits
  tests/s3/multipart_upload/test_multipart_upload.py
Labels: cla-signed, rose, Status: Unresolved Conversations

#1649 RBF for test_38090
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1640 GET/PUT object tagging - first test case
  tests/s3/versioning/test_get_put_object_tagging.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1647 2 more tests
  tests/s3/versioning/test_limits_tagging_versioning.py
Labels: cla-signed

#1655 CORTX_31879_TE_fix_1
  libs/s3/s3_versioning_common_test_lib.py
  libs/s3/s3_versioning_test_lib.py
  tests/s3/versioning/test_limits_tagging_versioning.py
Labels: cla-signed

#1653 CORTX:31878_TEST-40436
  tests/s3/versioning/test_delete_object_tagging.py
Labels: cla-signed

#1650 two more test cases : TEST-40431, 40432
  tests/s3/versioning/test_get_put_object_tagging.py
Labels: cla-signed

#1637 RBF for bucket Tagging TEST-5529
  tests/s3/test_bucket_tagging.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1643 Cortx 31866 ta
  commons/commands.py
  commons/helpers/pods_helper.py
  config/test_dtm_config.yaml
  libs/dtm/dtm_recovery.py
  tests/dtm/test_rgw_s3_process_restart.py
  tests/dtm/test_single_process_restart.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1654 TA for DeleteObjectTagging & Get object tags count using get-object
  tests/s3/test_object_tagging.py
Labels: cla-signed

#1646 Cortx 31882 putobject tagging happy path
  config/s3/s3_object_test.yaml
  tests/s3/test_object_tagging.py
Labels: cla-signed

#1645 create multipart upload with tagging
  config/s3/s3_object_test.yaml
  tests/s3/test_object_tagging.py
Labels: cla-signed

#1651 Ta 42255 42249
  config/test_dtm_config.yaml
  libs/dtm/dtm_recovery.py
  tests/dtm/test_rgw_s3_process_restart.py
  tests/dtm/test_single_process_restart.py
Labels: cla-signed

#1648 Added test for F-9H
  commons/constants.py
  comptests/prov/test_prov_k8s_cortx_cold_upgrade.py
  comptests/prov/test_prov_k8s_cortx_granular.py
  config/prov/prov_test.yaml
  libs/prov/prov_k8s_cortx_deploy.py
  libs/prov/prov_k8s_cortx_upgrade.py
  tests/prov/test_prov_k8s_cortx_upgrade.py
Labels: cla-signed

#1657 2 TC of get/put version tag - TEST-40433/40434
  tests/s3/versioning/test_get_put_object_tagging.py
Labels: cla-signed

#1656 CORTX: 31879_TE_2
  libs/s3/s3_versioning_common_test_lib.py
  tests/s3/versioning/test_get_put_object_tagging.py
  tests/s3/versioning/test_limits_tagging_versioning.py
Labels: cla-signed

#1662 Cortx 31932 ta multipart with versioning part 2
  libs/s3/s3_versioning_common_test_lib.py
  tests/s3/versioning/test_versioning_multipart_part_2.py
Labels: cla-signed

#1663 Added test for multidata pod
  commons/commands.py
  commons/params.py
  config/__init__.py
  config/prov/deploy_config.yaml
  config/prov/prov_test.yaml
  tests/prov/test_cont_deployment.py
  tests/prov/test_multiple_config_deploy.py
  tests/prov/test_prov_pods_deployment.py
Labels: cla-signed

#1670 RBF for F-71A quota tests
  config/csm/rest_response_data.yaml
  config/csm/test_rest_capacity.yaml
  libs/csm/rest/csm_rest_quota.py
  libs/s3/s3_misc.py
  tests/csm/rest/test_capacity_quota.py
Labels: cla-signed

#1665 Cortx 31936- Encoding support for k:v values for bucket tagging
  commons/exceptions.py
  libs/s3/s3_tagging_test_lib.py
  tests/s3/test_bucket_tagging.py
Labels: cla-signed

#1664 CORTX-31923: ListObjectVersions and DeleteObject with versioning RBF
  libs/s3/s3_test_lib.py
  libs/s3/s3_versioning.py
  libs/s3/s3_versioning_common_test_lib.py
  libs/s3/s3_versioning_test_lib.py
  tests/s3/versioning/test_list_object_versions.py
  tests/s3/versioning/test_versioning_delete_object.py
Labels: cla-signed

#1673 Added TEST-42852 Get object tags count using get-object
  tests/s3/test_object_tagging.py
Labels: cla-signed

#1660 TEST-40438 and 40439
  tests/s3/versioning/test_delete_object_tagging.py
Labels: cla-signed

#1676 DI first cut test cases for data corruption at motr level
  ci_tools/requirements-pip.txt
  commons/commands.py
  comptests/motr/test_motr_di.py
  libs/motr/motr_core_k8s_lib.py
  pytest.ini
Labels: ReadyToReview, cla-signed, Status: Waiting to be merged

#1677 #HOT_FIX main branch added
  comptests/prov/run-prov-sanity-multinode-k8s.groovy
Labels: cla-signed

#1683 Cortx 32236 te rvf multi part with versioning scenarios part2
  commons/constants.py
  libs/s3/s3_multipart.py
  libs/s3/s3_multipart_test_lib.py
  tests/s3/versioning/test_versioning_multipart.py
  tests/s3/versioning/test_versioning_multipart_part_2.py
Labels: cla-signed

#1688 CORTX-32336 - Fixes in test_cortx_port_scanner_netstat.py
  tests/security/requirement_ports.txt
  tests/security/test_cortx_port_scanner_netstat.py
Labels: cla-signed

#1604 Codacy fixes for health_helper and system_utils
  commons/helpers/health_helper.py
  commons/utils/system_utils.py
Labels: cla-signed, rose, Status: Waiting to be Reviewed

#1696 Quick Fixes for Popen
  commons/utils/system_utils.py
Labels: cla-signed

#1695 minor fixes for F-8I
  tests/ha/test_cluster_shutdown_start.py
Labels: cla-signed

#1652 Cortx 28307 f 71e rbf
  config/csm/test_rest_capacity.yaml
  libs/csm/rest/csm_rest_capacity.py
  libs/s3/s3_misc.py
  tests/csm/rest/test_capacity_usage.py
Labels: cla-signed

#1682 #Added S3IO-Operations
  comptests/prov/test_prov_k8s_cortx.py
  config/prov/prov_test.yaml
  libs/prov/prov_k8s_cortx_deploy.py
Labels: cla-signed

#1686 Added check_on_raw=True for existing tests
  config/csm/test_rest_capacity.yaml
  config/csm/test_rest_iam_user.yaml
  libs/csm/rest/csm_rest_quota.py
  libs/s3/s3_misc.py
  libs/s3/s3_multipart_test_lib.py
  tests/csm/rest/test_capacity_quota.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1700 Hot fixes for F-71E and F-71A tests
  libs/csm/rest/csm_rest_test_lib.py
  tests/csm/rest/test_capacity_usage.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1697 some fixes and minor alignments for CORTX-32238
  tests/s3/versioning/test_delete_object_tagging.py
  tests/s3/versioning/test_get_put_object_tagging.py
Labels: cla-signed

#1690 added hot fixes in iam bkt cruds
  config/ha_test.yaml
  libs/ha/ha_common_libs_k8s.py
  tests/ha/test_control_pod_restart.py
Labels: cla-signed

#1698 CORTX-32253: Fixes for DeleteObject tests
  libs/s3/s3_versioning_common_test_lib.py
  tests/s3/versioning/test_delete_object_tagging.py
  tests/s3/versioning/test_get_bucket_versioning.py
  tests/s3/versioning/test_get_put_object_tagging.py
  tests/s3/versioning/test_limits_tagging_versioning.py
  tests/s3/versioning/test_list_object_versions.py
  tests/s3/versioning/test_put_bucket_versioning.py
  tests/s3/versioning/test_versioning_delete_object.py
  tests/s3/versioning/test_versioning_get_head_object.py
  tests/s3/versioning/test_versioning_put_object.py
Labels: cla-signed

#1675 New-suspend
  commons/constants.py
  pytest.ini
  tests/prov/test_prov_k8s_cortx_upgrade.py
Labels: cla-signed

#1706 Enable TEST - 42284
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1709 bug fix
  tests/s3/multipart_upload/test_multipart_getput.py
Labels: cla-signed

#1689 Cortx 32237 f 33 a 2
  libs/s3/s3_versioning_common_test_lib.py
  tests/s3/versioning/test_versioning_multipart.py
Labels: cla-signed

#1685 Policy operations are moved to test_user_policy_crud.py
  comptests/s3/test_rest_api_rgw.py
  comptests/s3/test_user_policy_crud.py
  requirements.txt
Labels: cla-signed

#1679 Added TEST-42257
  commons/params.py
  config/__init__.py
  config/dtm/dtm_config.yaml
  config/dtm/test_dtm_config.yaml
  libs/dtm/dtm_recovery.py
  libs/s3/s3_core_lib.py
  tests/dtm/test_rgw_s3_process_restart.py
  tests/dtm/test_single_m0d_process_restart.py
Labels: cla-signed

#1694 DPS_hotfixes_1
  config/dtm/test_dtm_config.yaml
  libs/dtm/dtm_recovery.py
  tests/dtm/test_rgw_s3_process_restart.py
  tests/dtm/test_single_m0d_process_restart.py
Labels: cla-signed

#1711 Dps quick fix
  tests/dtm/test_rgw_s3_process_restart.py
  tests/dtm/test_single_m0d_process_restart.py
  tests/iostability/test_iostability_degraded_path.py
Labels: cla-signed

#1712 f23e test cases related to data corruption and libraries for parity and checksum corruption.
  commons/commands.py
  comptests/motr/test_motr_di.py
  libs/motr/emap_fi_adapter.py
  libs/motr/motr_core_k8s_lib.py
  libs/motr/motr_di_validation.py
  tools/motr_dc/__init__.py
  tools/setup_update/setup_entry.py
Labels: cla-signed

#1702 Cortx 32196 tagging TE/RVF
  tests/s3/test_object_tagging.py
Labels: cla-signed

#1701 Cortx-29601: RBF for Object tagging versioning
  config/s3/s3_config.yaml
  tests/s3/versioning/test_delete_object_tagging.py
  tests/s3/versioning/test_limits_tagging_versioning.py
Labels: cla-signed

#1710 CORTX_32185
  config/ha_test.yaml
  libs/ha/ha_common_libs_k8s.py
  scripts/s3_bench/s3bench.py
  tests/ha/test_data_pod_failure.py
  tests/ha/test_ha_pod_restart.py
  tests/ha/test_server_pod_failure.py
Labels: cla-signed

#1717 Cortx 32213
  config/csm/csm_config.yaml
  config/csm/test_rest_capacity.yaml
  libs/csm/rest/csm_rest_iamuser.py
  libs/csm/rest/csm_rest_quota.py
  tests/csm/rest/test_capacity_quota.py
  tests/csm/rest/test_capacity_usage.py
  tests/csm/rest/test_iam_users.py
Labels: cla-signed

#1722 Added Overwrite tests for F-71a with comments addressed
  config/csm/test_rest_capacity.yaml
  tests/csm/rest/test_capacity_quota.py
Labels: cla-signed

#1716 F-71A: Automation of test_40638 and test_40639
  config/csm/test_rest_capacity.yaml
  tests/csm/rest/test_capacity_quota.py
Labels: cla-signed
