Repository Seagate/cortx-test, pull requests merged in 2022-08, with the labels that each got.

#1784 Cortx 33502 lib
  commons/commands.py
  commons/constants.py
  libs/motr/motr_core_k8s_lib.py
Labels: cla-signed

#1782 Server pod restart (2 tests)
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed

#1783 CORTX-33279 F-40E 2 Tests TA
  config/csm/test_jmeter.yaml
  scripts/jmx_files/CSM_create_IAM_user_Loaded.jmx
  tests/csm/rest/test_csm_load.py
Labels: cla-signed

#1775 Cortx 33318 2 tests modification
  tests/ha/single_pod_restart/test_data_pod_restart.py
Labels: cla-signed

#1773 TEST-19842 Automated Parallel Copy Operation of same source and destination
  libs/s3/s3_multipart_test_lib.py
  tests/s3/copy_object/test_copy_object.py
  tests/s3/copy_object/test_parallel_copy_object.py
Labels: cla-signed

#1780 TA: Simple and Multipart copy object with destination object tag
  tests/s3/copy_object/test_copy_object_tag.py
Labels: cla-signed

#1777 CORTX-33458 RGW error message correction seen for copy operation of more than 5GB object
  commons/error_messages.py
Labels: cla-signed

#1776 rvf for copyobj - CORTX-33463
  commons/error_messages.py
  tests/s3/copy_object/test_copy_object.py
Labels: cla-signed

#1757 Cortx-33435_collect_stats
  commons/commands.py
  commons/constants.py
  commons/utils/top_stats_collection_utils.py
  config/iostability_test.yaml
  scripts/io_stability/collect-k8s-stats.sh
  scripts/io_stability/profiling.yaml
  tests/iostability/test_iostability_degraded_path.py
  tests/iostability/test_iostability_happy_path.py
Labels: cla-signed

#1788 Server pod restart (2 tests)
  config/ha_test.yaml
  tests/ha/single_pod_restart/test_server_pod_restart.py
Labels: cla-signed

#1787 Cortx 33318 2 more tests
  tests/ha/single_pod_restart/test_data_pod_restart.py
Labels: cla-signed

#1785 data_pod_restart_optimization
  tests/ha/single_pod_restart/test_data_pod_restart.py
Labels: cla-signed

#1790 Jmeter lib for parallel CSM user creation and deletion
  commons/commands.py
  libs/csm/rest/csm_rest_parallel_operations.py
  scripts/jmx_files/CSM_Create_N_Manage_Users.jmx
  scripts/jmx_files/CSM_Delete_N_CsmUsers.jmx
Labels: cla-signed

#1789 Server pod restart (2 tests)
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed

#1791 CORTX-333872 : F-40E 2 Tests TA
  config/csm/test_jmeter.yaml
  scripts/jmx_files/CSM_Poll_Degraded_Capacity.jmx
  scripts/jmx_files/CSM_Poll_User_Capacity.jmx
  tests/csm/rest/test_csm_load.py
Labels: cla-signed

#1793 support bundle tests with parameters
  commons/constants.py
  commons/utils/support_bundle_utils.py
  tests/cft/test_r2_support_bundle.py
Labels: cla-signed

#1795 Fix the server pod count and close ssh connection
  config/prov/prov_test.yaml
  libs/motr/motr_core_k8s_lib.py
  libs/prov/prov_k8s_cortx_deploy.py
  tests/prov/test_multiple_config_deploy.py
  tests/prov/test_prov_pods_deployment.py
Labels: cla-signed

#1799 data pod failure test suite changes for V9
  libs/ha/ha_common_libs_k8s.py
  tests/ha/single_pod_failure/test_data_pod_failure.py
  tests/ha/single_pod_failure/test_server_pod_failure.py
Labels: cla-signed

#1794 Changes for stateful set - V0.9.0 in IO stability degraded test.
  tests/iostability/test_iostability_degraded_path.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1798 cortx-33340
  libs/ha/ha_common_libs_k8s.py
  tests/ha/single_pod_restart/test_server_pod_restart.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1800 Added support for log devices
  config/prov/prov_test.yaml
  libs/prov/prov_k8s_cortx_deploy.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1802 CORTX-33335 versioning_with_server_pod_restart
  config/ha_test.yaml
  libs/ha/ha_common_libs_k8s.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1803 Single server pod resatrt - TEST-44837, 44846
  FETCH_HEAD
  tests/ha/single_pod_restart/test_server_pod_restart.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: Status: Waiting to be Reviewed

#1797 CORTX-33464:F-20A: TA: Handle parallel copy operation of the same source and destination
  tests/s3/copy_object/test_parallel_copy_object.py
Labels: cla-signed, Status: Changes requested

#1808 Cortx 33329 data pod restart testsuite
  config/common_config.yaml
  tests/ha/single_pod_failure/test_data_pod_failure.py
  tests/ha/single_pod_failure/test_server_pod_failure.py
  tests/ha/single_pod_restart/test_data_pod_restart.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1807 Cortx 33341
  config/ha_test.yaml
  libs/ha/ha_common_libs_k8s.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1806 TA for simultaneous delete with copy object
  tests/s3/copy_object/test_copy_obj_simultaneous_del.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1805 Cortx-33427 Mail notification changes
  commons/mail_script_utils.py
  libs/iostability/iostability_lib.py
  tests/iostability/test_iostability_degraded_path.py
  tests/iostability/test_iostability_happy_path.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1812 sanity marker added in tagging tests
  tests/s3/test_bucket_tagging.py
  tests/s3/test_object_tagging.py
  tests/s3/versioning/test_delete_object_tagging.py
  tests/s3/versioning/test_get_put_object_tagging.py
Labels: cla-signed

#1804 Added test TEST-45716
  commons/constants.py
  comptests/motr/test_motr_di.py
  libs/motr/emap_fi_adapter.py
  libs/motr/motr_core_k8s_lib.py
Labels: cla-signed, Status: Waiting to be Reviewed

#1811 Cortx 33302 - 4 New tests added and 1 test fixed
  config/csm/test_jmeter.yaml
  config/csm/test_rest_resource_limit.yaml
  libs/csm/csm_interface.py
  libs/csm/extensions/csm_prov_ext.py
  libs/csm/rest/csm_rest_parallel_operations.py
  tests/csm/rest/test_csm_load.py
  tests/csm/rest/test_csm_resource_limit.py
Labels: cla-signed

#1809 one Server pod restart - TEST-44840, 44838, 44841
  tests/ha/single_pod_restart/test_server_pod_restart.py
Labels: cla-signed

#1816 Cortx 33386
  commons/constants.py
  config/csm/csm_config.yaml
  libs/csm/rest/csm_rest_acc_capacity.py
  libs/csm/rest/csm_rest_alert.py
  libs/csm/rest/csm_rest_audit_logs.py
  libs/csm/rest/csm_rest_bucket.py
  libs/csm/rest/csm_rest_capacity.py
  libs/csm/rest/csm_rest_cluster.py
  libs/csm/rest/csm_rest_core_lib.py
  libs/csm/rest/csm_rest_csmuser.py
  libs/csm/rest/csm_rest_iamuser.py
  libs/csm/rest/csm_rest_information.py
  libs/csm/rest/csm_rest_parallel_operations.py
  libs/csm/rest/csm_rest_quota.py
  libs/csm/rest/csm_rest_s3user.py
  libs/csm/rest/csm_rest_stats.py
  libs/csm/rest/csm_rest_system_health.py
  tests/csm/gui/test_server_os_gui_alerts.py
  tests/csm/rest/test_ldap_security.py
Labels: cla-signed

#1817 modified as per dev changes those comply with aws
  commons/error_messages.py
  tests/s3/copy_object/test_copy_object.py
Labels: cla-signed

#1818 Codacy fixes for security warnings
  commons/constants.py
  libs/prov/provisioner.py
  scripts/jenkins_job/aws_configure.py
  scripts/jenkins_job/client_conf.py
Labels: cla-signed

#1796 Added library and one test for F-87N Query Deployment
  config/csm/csm_config.yaml
  libs/csm/csm_interface.py
  libs/csm/rest/csm_rest_query_deployment.py
  tests/csm/rest/test_query_deployment.py
Labels: Status: Waiting to be Reviewed

#1819 HA_reg_break_quickFix
  tests/ha/single_pod_failure/test_data_pod_failure.py
Labels: cla-signed

#1815 Cortx 33515 testcases
  comptests/motr/test_motr_di.py
  config/di_config.yaml
Labels: cla-signed

#1823 CORTX-33338 _ HA_api_test_moved
  tests/ha/single_pod_restart/test_data_pod_restart.py
  tests/ha/single_pod_restart/test_data_pod_restart_api.py
Labels: cla-signed

#1824 Hotfix copy object te
  tests/s3/copy_object/test_copy_object.py
Labels: cla-signed

#1828 change in cluster.conf path as gconf moved to consul
  commons/commands.py
Labels: cla-signed

#1821 Data server pod restart - Test-45510
  tests/ha/single_pod_restart/test_data_server_pod_restart.py
Labels: cla-signed

#1822 CORTX-33336 Delete_cleanup_update_ha_lib_reorg_ta_TEST-45641
  libs/ha/ha_common_api_libs_k8s.py
  libs/ha/ha_common_libs_k8s.py
  tests/ha/single_pod_restart/test_data_pod_restart.py
  tests/ha/single_pod_restart/test_data_pod_restart_api.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed

#1825 cortx-33358
  config/ha_test.yaml
  libs/ha/ha_common_libs_k8s.py
  tests/ha/single_pod_restart/test_server_pod_restart.py
Labels: cla-signed

#1830 Fail on unauthorized JIRA access
  commons/utils/jira_utils.py
Labels: cla-signed

#1826 F-87N Query Deployment tests
  config/csm/test_rest_query_deployment.yaml
  libs/csm/rest/csm_rest_query_deployment.py
  libs/csm/rest/csm_rest_test_lib.py
  tests/csm/rest/test_capacity_usage.py
  tests/csm/rest/test_query_deployment.py
Labels: cla-signed

#1827 First test-40369
  commons/commands.py
  scripts/cicd_k8s/run-sanity-multinode-rgw.groovy
  tests/ha/control_pod/test_control_pod_restart.py
Labels: cla-signed

#1813 CORTX-33465 TA for simultaneous delete with copy object
  commons/error_messages.py
  tests/s3/copy_object/test_copy_obj_simultaneous_del.py
Labels: cla-signed

#1836 Cortx 33295 resources
  config/prov/prov_test.yaml
  libs/prov/prov_k8s_cortx_deploy.py
  tests/prov/test_multiple_config_deploy.py
Labels: cla-signed

#1837 latest motr di tests and lib updates - s76
  commons/constants.py
  commons/params.py
  comptests/motr/test_motr_di.py
  libs/motr/emap_fi_adapter.py
  libs/motr/motr_core_k8s_lib.py
Labels: cla-signed

#1832 Cortx 33358 1
  commons/commands.py
  commons/helpers/pods_helper.py
  commons/utils/system_utils.py
  libs/ha/ha_common_libs_k8s.py
  scripts/s3_bench/s3bench.py
  tests/ha/single_pod_restart/test_server_pod_restart.py
Labels: cla-signed

#1834 Cortx 33333 part2
  tests/ha/single_pod_restart/test_data_server_pod_restart.py
  tests/ha/single_pod_restart/test_data_server_pod_restart_api.py
Labels: cla-signed

#1835 Cortx 33331 TEST-40387
  tests/ha/control_pod/test_control_pod_restart.py
Labels: cla-signed

#1820 code optimization
  libs/s3/s3_common_test_lib.py
  tests/s3/copy_object/test_copy_obj_simultaneous_del.py
  tests/s3/copy_object/test_copy_object.py
  tests/s3/copy_object/test_copy_object_tag.py
  tests/s3/copy_object/test_parallel_copy_object.py
Labels: cla-signed

#1838 CORTX-33338_ta_TEST-45639_TEST-45640
  tests/ha/single_pod_restart/test_data_pod_restart_api.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed

#1831 CORTX-33339_TA_test_45637_ test_45638
  tests/ha/single_pod_restart/test_data_pod_restart_api.py
  tests/ha/single_pod_restart/test_server_pod_restart_api.py
Labels: cla-signed

#1840 Data and Server pod restart - TEST-45529, 45536
  tests/ha/single_pod_restart/test_data_server_pod_restart.py
Labels: cla-signed

#1841 CORTX-32078 - Updated ceph execution script
  ceph_s3tests_runner.py
  config/__init__.py
  scripts/ceph_s3_tests/cortx_rgw_template.conf
Labels: cla-signed

#1846 Cortx 33332
  config/ha_test.yaml
  tests/ha/control_pod/test_control_pod_restart.py
Labels: cla-signed

#1833 Cortx-33442_TA_multi_process_restart
  commons/helpers/pods_helper.py
  commons/params.py
  config/__init__.py
  libs/dtm/dtm_recovery.py
  tests/dtm/test_multi_m0d_process_restart.py
Labels: cla-signed

#1842 CORTX-33294 : F-40E Degraded Mode Tests RBF-TA
  config/csm/test_jmeter.yaml
  config/csm/test_rest_account_capacity.yaml
  libs/csm/extensions/csm_ext.py
  tests/csm/rest/test_account_capacity.py
  tests/csm/rest/test_capacity_usage.py
  tests/csm/rest/test_csm_load.py
  tests/csm/rest/test_csm_resource_limit.py
Labels: cla-signed

#1844 Cortx 33520 test
  commons/commands.py
  comptests/motr/test_motr_di.py
  config/di_config.yaml
  libs/motr/emap_fi_adapter.py
  libs/motr/motr_core_k8s_lib.py
Labels: cla-signed

#1843 CORTX-33466: TA Check quota on the destination bucket
  commons/error_messages.py
  libs/csm/rest/csm_rest_iamuser.py
  libs/s3/s3_misc.py
  tests/s3/copy_object/test_copy_object_quota.py
Labels: cla-signed

#1849 CORTX-33301 F-40E 2 Tests TA
  config/csm/test_jmeter.yaml
  libs/csm/rest/csm_rest_parallel_operations.py
  scripts/jmx_files/CSM_Create_N_Monitor_Create_List_N_IAM.jmx
  scripts/jmx_files/CSM_Create_N_Monitor_Create_N_IAM_Set_Quota.jmx
  tests/csm/rest/test_csm_load.py
Labels: cla-signed
